server:
  port: 8080

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom_cache?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234

router:
  jdbc:
    datasource:
      hot:
        url: jdbc:mysql://localhost:3306/jzo2o_demo?useUnicode=true
        username: root
        password: 1234
      cold:
        url: jdbc:mysql://localhost:3306/jzo2o_demo_cold?useUnicode=true
        username: root
        password: 1234