server:
  port: 8080

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom_cache?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234