spring:
  profiles:
    active: dev
  rabbitmq:
    host: ${spring.rabbitmq.host}
    port: ${spring.rabbitmq.port}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}

server:
  port: ${server.port:8080}

logging:
  level:
    root: ${logging.level.root:info}

redis:
  host: ${redis.host}
  port: ${redis.port}
  password: ${redis.password}

router:
  jdbc:
    datasource:
      hot:
        url: ${router.jdbc.datasource.hot.url}
        username: ${router.jdbc.datasource.hot.username}
        password: ${router.jdbc.datasource.hot.password}
      cold:
        url: ${router.jdbc.datasource.cold.url}
        username: ${router.jdbc.datasource.cold.username}
        password: ${router.jdbc.datasource.cold.password}
